version: '3.5'

services: 
  users-service-db:
    image: mysql:5.7.20
    container_name: users-service-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports: 
      - 7201:3306
    volumes:
      - users-service-data:/var/lib/mysql

  chat-service-db:
    image: mysql:5.7.20
    container_name: chat-service-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports: 
      - 7200:3306
    volumes:
      - chat-service-data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 7300:80
    volumes: 
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    depends_on:
      - chat-service-db
      - users-service-db

  chat-app:
    container_name: chat-app
    build:
      context: ./chat-app
    depends_on:
      - api-gateway
    env_file: ./chat-app/.env
    ports: 
      - 7001:7001
  
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
    depends_on: 
      - chat-service
      - users-service
    ports:
      - 7000:7000

  chat-service:
    container_name: chat-service
    build: 
      context: ./chat-service
    depends_on:
      - chat-service-db
    ports:
      - 7100:7100

  users-service:
    container_name: users-service
    build:
      context: ./users-service
    depends_on:
      - users-service-db
    ports:
      - 7101:7101
    command: sh -c "yarn db:migrate && yarn watch"

volumes:
  users-service-data:
  chat-service-data: